import enum


class PhraseTypes(enum.Enum):
    WELCOME_PHRASE = 0
    ASK_QUESTION_PHRASE = 1
    PLEASE_WAIT_PHRASE = 2
    PLEASE_RANK_PHRASE = 3
    HELP_PHRASE = 4
    ASK_QUESTION_IN_GROUP_PHRASE = 5
