"""created_db_schema

Revision ID: 0d7d173d2941
Revises: 0365394efdfe
Create Date: 2020-03-22 14:24:06.173569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7d173d2941'
down_revision = '0365394efdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('answer', sa.Column('msg_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('predictor_fk', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('question_fk', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('text', sa.String(), nullable=False))
    op.create_foreign_key(None, 'answer', 'question', ['question_fk'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'answer', 'predictor', ['predictor_fk'], ['id'], ondelete='RESTRICT')
    op.add_column('knowledge_answer', sa.Column('text', sa.String(), nullable=False))
    op.add_column('knowledge_pdf_content', sa.Column('content', sa.String(), nullable=False))
    op.add_column('knowledge_pdf_content', sa.Column('content_page', sa.Integer(), nullable=False))
    op.add_column('knowledge_pdf_content', sa.Column('content_paragraph', sa.Integer(), nullable=False))
    op.add_column('knowledge_question', sa.Column('knowledge_answer_fk', sa.Integer(), nullable=True))
    op.add_column('knowledge_question', sa.Column('text', sa.String(), nullable=False))
    op.create_foreign_key(None, 'knowledge_question', 'knowledge_answer', ['knowledge_answer_fk'], ['id'])
    op.add_column('predictor', sa.Column('description', sa.String(), nullable=False))
    op.add_column('predictor', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'predictor', ['name'])
    op.add_column('question', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('question', sa.Column('msg_id', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('text', sa.String(), nullable=False))
    op.add_column('question', sa.Column('user_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'user', ['user_fk'], ['tg_id'], ondelete='RESTRICT')
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('user_tg_id_key', 'user', ['tg_id'])
    op.drop_column('user', 'username')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'user_fk')
    op.drop_column('question', 'text')
    op.drop_column('question', 'msg_id')
    op.drop_column('question', 'created_at')
    op.drop_column('question', 'chat_id')
    op.drop_constraint(None, 'predictor', type_='unique')
    op.drop_column('predictor', 'name')
    op.drop_column('predictor', 'description')
    op.drop_constraint(None, 'knowledge_question', type_='foreignkey')
    op.drop_column('knowledge_question', 'text')
    op.drop_column('knowledge_question', 'knowledge_answer_fk')
    op.drop_column('knowledge_pdf_content', 'content_paragraph')
    op.drop_column('knowledge_pdf_content', 'content_page')
    op.drop_column('knowledge_pdf_content', 'content')
    op.drop_column('knowledge_answer', 'text')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'text')
    op.drop_column('answer', 'rating')
    op.drop_column('answer', 'question_fk')
    op.drop_column('answer', 'predictor_fk')
    op.drop_column('answer', 'msg_id')
    op.drop_column('answer', 'created_at')
    # ### end Alembic commands ###
