"""fixed implementation support chat btn

Revision ID: 1cd309619478
Revises: cade5a0aadad
Create Date: 2020-03-31 20:26:18.661263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd309619478'
down_revision = 'cade5a0aadad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_question', sa.Column('question_chat_id', sa.Integer(), nullable=False))
    op.drop_constraint('expert_question_question_user_fk_fkey', 'expert_question', type_='foreignkey')
    op.drop_column('expert_question', 'question_user_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_question', sa.Column('question_user_fk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('expert_question_question_user_fk_fkey', 'expert_question', 'user', ['question_user_fk'], ['tg_id'])
    op.drop_column('expert_question', 'question_chat_id')
    # ### end Alembic commands ###
