"""implementation support chat btn

Revision ID: 84b231004571
Revises: f588b4a04c3b
Create Date: 2020-03-31 19:28:03.890341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b231004571'
down_revision = 'f588b4a04c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_msg_id', sa.Integer(), nullable=False),
    sa.Column('expert_question_chat_id', sa.Integer(), nullable=False),
    sa.Column('expert_question_msg_id', sa.Integer(), nullable=False),
    sa.Column('expert_answer_msg_id', sa.Integer(), nullable=True),
    sa.Column('expert_answer_text', sa.String(), nullable=True),
    sa.Column('expert_user_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expert_user_fk'], ['user.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expert_question')
    # ### end Alembic commands ###
