"""fixed implementation support chat btn

Revision ID: cade5a0aadad
Revises: 84b231004571
Create Date: 2020-03-31 20:20:41.006330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cade5a0aadad'
down_revision = '84b231004571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_question', sa.Column('question_user_fk', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'expert_question', 'user', ['question_user_fk'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expert_question', type_='foreignkey')
    op.drop_column('expert_question', 'question_user_fk')
    # ### end Alembic commands ###
