"""changed_nullables

Revision ID: f588b4a04c3b
Revises: 0d7d173d2941
Create Date: 2020-03-22 14:31:23.489761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f588b4a04c3b'
down_revision = '0d7d173d2941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'predictor_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('answer', 'question_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('knowledge_question', 'knowledge_answer_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question', 'user_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'user_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('knowledge_question', 'knowledge_answer_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('answer', 'question_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('answer', 'predictor_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
